// ********RoostGPT********
/*
Test generated by RoostGPT for test junit4-petstore using AI Type  and AI Model

ROOST_METHOD_HASH=getId_ba482bff4a
ROOST_METHOD_SIG_HASH=getId_38c14d960a

"""
Scenario 1: Test to verify the correct ID is returned

Details:
  TestName: testGetIdReturnsCorrectId
  Description: This test aims to verify that the getId method returns the correct id of the OrderLine object.
Execution:
  Arrange: Create an OrderLine object and set its id using setId method.
  Act: Invoke the getId method on the OrderLine object.
  Assert: Use assertEquals to compare the returned id with the set id.
Validation:
  The assertion verifies that the getId method returns the correct id of the OrderLine object. This test is important to ensure that the getter method for id is working correctly.

Scenario 2: Test to check getId returns null for an OrderLine object with no id set

Details:
  TestName: testGetIdReturnsNullForNoIdSet
  Description: This test aims to verify that the getId method returns null when no id is set for the OrderLine object.
Execution:
  Arrange: Create an OrderLine object without setting an id.
  Act: Invoke the getId method on the OrderLine object.
  Assert: Use assertNull to check if the returned id is null.
Validation:
  The assertion verifies that the getId method returns null when no id is set for the OrderLine object. This test is important to ensure correct behavior of the getId method when no id is set.

Scenario 3: Test to check getId returns the last set id for an OrderLine object

Details:
  TestName: testGetIdReturnsLastSetId
  Description: This test aims to verify that the getId method returns the last set id for the OrderLine object.
Execution:
  Arrange: Create an OrderLine object and set its id multiple times using setId method.
  Act: Invoke the getId method on the OrderLine object.
  Assert: Use assertEquals to compare the returned id with the last set id.
Validation:
  The assertion verifies that the getId method returns the last set id for the OrderLine object. This test is important to ensure that the getId method returns the most recent id set.
"""
*/

// ********RoostGPT********

package org.agoncal.application.petstore.model;

import org.junit.Test;
import org.junit.experimental.categories.Category;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import javax.persistence.*;
import javax.validation.constraints.Min;
import java.io.Serializable;
import java.util.Objects;

public class OrderLineGetIdTest {

	@Test
	@Category(Categories.valid.class)
	public void testGetIdReturnsCorrectId() {
		// Arrange
		OrderLine orderLine = new OrderLine();
		Long expectedId = 123L;
		orderLine.setId(expectedId);
		// Act
		Long actualId = orderLine.getId();
		// Assert
		assertEquals(expectedId, actualId);
	}

	@Test
	@Category(Categories.valid.class)
	public void testGetIdReturnsNullForNoIdSet() {
		// Arrange
		OrderLine orderLine = new OrderLine();
		// Act
		Long actualId = orderLine.getId();
		// Assert
		assertNull(actualId);
	}

	@Test
	@Category(Categories.valid.class)
	public void testGetIdReturnsLastSetId() {
		// Arrange
		OrderLine orderLine = new OrderLine();
		Long expectedId = 456L;
		orderLine.setId(123L);
		orderLine.setId(expectedId);
		// Act
		Long actualId = orderLine.getId();
		// Assert
		assertEquals(expectedId, actualId);
	}

}